### ISSUE TITLE
第二次执行时报错

### ISSUE THREAD

**Issue by lonelyion** [fuhaiwei/bmoe-2017#1]
```
文件写入成功: current.txt
失败次数大于10次，链接为：http://bangumi.bilibili.com/moe/2017/2/api/realtime/votes?page=3&pagesize=50
失败次数大于10次，链接为：http://bangumi.bilibili.com/moe/2017/2/api/realtime/votes?page=1&pagesize=50
失败次数大于10次，链接为：http://bangumi.bilibili.com/moe/2017/2/api/realtime/votes?page=0&pagesize=50java.nio.charset.MalformedInputException: Input length = 1

失败次数大于10次，链接为：http://bangumi.bilibili.com/moe/2017/2/api/realtime/votes?page=2&pagesize=50  at java.nio.charset.CoderResult.throwException(CoderResult.java:281)

失败次数大于10次，链接为：http://bangumi.bilibili.com/moe/2017/2/api/realtime/votes?page=4&pagesize=50  at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)

        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at java.nio.file.Files.readAllLines(Files.java:3205)
        at java.nio.file.Files.readAllLines(Files.java:3242)
        at fuhaiwei.bmoe2017.FileUtil.readText(FileUtil.java:12)
        at fuhaiwei.bmoe2017.Fetcher.fetchData(Fetcher.java:84)
        at fuhaiwei.bmoe2017.Fetcher.lambda$fetchData$0(Fetcher.java:54)
        at java.lang.Thread.run(Thread.java:748)
java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at java.nio.file.Files.readAllLines(Files.java:3205)
        at java.nio.file.Files.readAllLines(Files.java:3242)
        at fuhaiwei.bmoe2017.FileUtil.readText(FileUtil.java:12)
        at fuhaiwei.bmoe2017.Fetcher.fetchData(Fetcher.java:84)
        at fuhaiwei.bmoe2017.Fetcher.lambda$fetchData$0(Fetcher.java:54)
        at java.lang.Thread.run(Thread.java:748)
java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at java.nio.file.Files.readAllLines(Files.java:3205)
        at java.nio.file.Files.readAllLines(Files.java:3242)
        at fuhaiwei.bmoe2017.FileUtil.readText(FileUtil.java:12)
        at fuhaiwei.bmoe2017.Fetcher.fetchData(Fetcher.java:84)
        at fuhaiwei.bmoe2017.Fetcher.lambda$fetchData$0(Fetcher.java:54)
        at java.lang.Thread.run(Thread.java:748)
java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at java.nio.file.Files.readAllLines(Files.java:3205)
        at java.nio.file.Files.readAllLines(Files.java:3242)
        at fuhaiwei.bmoe2017.FileUtil.readText(FileUtil.java:12)
        at fuhaiwei.bmoe2017.Fetcher.fetchData(Fetcher.java:84)
        at fuhaiwei.bmoe2017.Fetcher.lambda$fetchData$0(Fetcher.java:54)
        at java.lang.Thread.run(Thread.java:748)
java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at java.nio.file.Files.readAllLines(Files.java:3205)
        at java.nio.file.Files.readAllLines(Files.java:3242)
        at fuhaiwei.bmoe2017.FileUtil.readText(FileUtil.java:12)
        at fuhaiwei.bmoe2017.Fetcher.fetchData(Fetcher.java:84)
        at fuhaiwei.bmoe2017.Fetcher.lambda$fetchData$0(Fetcher.java:54)
        at java.lang.Thread.run(Thread.java:748)
文件写入成功: 2017-08-09-13-27-17.txt
文件写入成功: 2017-08-09-13-27-17.txt
```

但是两个txt都没有数据，我一开始还以为是Windows的问题，结果到Bash上还是

**Comment by fuhaiwei** [comment]
这是因为访问太多IP被B站给Ban了，最新版已经加入增量更新。
另外，我的网站现在运行一切正常了，如果是简单的查看可以考虑从网站上看。
如果还是要自己运行，就用最新版吧（另外被B站Ban几个小时就会解除）。

**Comment by lonelyion** [comment]
只是自己clone下来玩玩，看还是经常看网站上的。
刚才我合并了最新的代码，发现issue依然存在。我觉得原因可能是因为我的编译方法跟你不一样？

**Comment by fuhaiwei** [comment]
等解封了，最好1点开始运行，如果下午开始可能一次就被封了。

**Comment by fuhaiwei** [comment]
下午可能数据超过一千条了，马上就会被封掉IP

**Comment by lonelyion** [comment]
不对，如果我把data里面的删除了再跑，就没有问题
